# Generated by jeweler
# DO NOT EDIT THIS FILE DIRECTLY
# Instead, edit Jeweler::Tasks in Rakefile, and run 'rake gemspec'
# -*- encoding: utf-8 -*-

Gem::Specification.new do |s|
  s.name = "enumerated_attribute"
  s.version = "0.3.1"

  s.required_rubygems_version = Gem::Requirement.new("> 1.3.1") if s.respond_to? :required_rubygems_version=
  s.authors = ["Jeff Patmon", "Turadg Aleahmad"]
  s.date = "2011-09-02"
  s.description = "Add enumerated attributes to your models and expose them in drop-down lists in your views"
  s.email = ["jpatmon@gmail.com", "turadg@aleahmad.net"]
  s.extra_rdoc_files = [
    "LICENSE",
    "README.rdoc"
  ]
  s.files = [
    ".gitignore",
    "CHANGELOG.rdoc",
    "LICENSE",
    "README.rdoc",
    "Rakefile",
    "init.rb",
    "lib/enumerated_attribute.rb",
    "lib/enumerated_attribute/attribute.rb",
    "lib/enumerated_attribute/attribute/arguments.rb",
    "lib/enumerated_attribute/attribute/attribute_descriptor.rb",
    "lib/enumerated_attribute/attribute/class_methods.rb",
    "lib/enumerated_attribute/attribute/instance_methods.rb",
    "lib/enumerated_attribute/integrations.rb",
    "lib/enumerated_attribute/integrations/default.rb",
    "lib/enumerated_attribute/integrations/object.rb",
    "lib/enumerated_attribute/method_definition_dsl.rb",
    "spec/car.rb",
    "spec/cfg.rb",
    "spec/inheritance_classes.rb",
    "spec/inheritance_spec.rb",
    "spec/new_and_method_missing_spec.rb",
    "spec/plural.rb",
    "spec/poro_spec.rb",
    "spec/rcov.opts",
    "spec/spec.opts",
    "spec/tractor.rb"
  ]
  s.homepage = "http://github.com/jeffp/enumerated_attribute/"
  s.require_paths = ["lib"]
  s.rubygems_version = "1.8.10"
  s.summary = "Enumerated model attributes and view helpers"
  s.test_files = ["spec/inheritance_spec.rb", "spec/new_and_method_missing_spec.rb", "spec/poro_spec.rb"]

  if s.respond_to? :specification_version then
    s.specification_version = 3

    if Gem::Version.new(Gem::VERSION) >= Gem::Version.new('1.2.0') then
      s.add_runtime_dependency(%q<meta_programming>, [">= 0.2.1"])
    else
      s.add_dependency(%q<meta_programming>, [">= 0.2.1"])
    end
  else
    s.add_dependency(%q<meta_programming>, [">= 0.2.1"])
  end
end

